### ISSUE TITLE
Internal Server Errer bei Klick auf Update

### ISSUE THREAD

**Issue by markusk** [studio-connect/webapp_backup#1]
Hallo,

mein Studioconnect wurde freundlicherweise beim vorletzten Podlove Workshop eingerichtet.
Nun wollte ich es endlich testen (und updaten). Das Update bringt jedoch gleich die obige Fehlermeldung...

Im Log sehe ich scheinbar keine Fehlermeldungen, außer:
Jan 08 22:01:31 studio-connect-ad97ee gunicorn[168]: ValueError: '14.4.3-alpha' is not in list

**Comment by sreimers** [comment]
Hi Markus,

ja das liegt an der Projekt Umbenennung zu Studio Link. Ich bereite gerade eine neue Version vor. Eigentlich dachte ich alle wären schon auf 14.5.0, so kann man sich täuschen ;-)

Du kannst aber mal probieren als Root Benutzer selbst auf die neue Version zu wechseln:

$ curl -L https://raw.githubusercontent.com/studio-link/images/master/bootstrap.sh | bash

Maik müsste das dann ebenfalls machen. Allerdings bin ich selbst noch nicht dazu gekommen diesen Versionssprung zu testen, das mache ich sobald die neue Version steht (dauert noch 1-2 Wochen).

Was aber wenn alles schief geht, getestet ist, ist die Grundinstallation unter:

http://archlinuxarm.org/platforms/armv7/ti/beaglebone-black

Wichtig ist den zweiten Teil, sprich die Installation auf der internen eMMC Karte zu absolvieren.

Hier der Link zur entsprechenden README: https://github.com/Studio-Link/images/blob/master/README.md

Viele Grüße,

Sebastian

**Comment by markusk** [comment]
Hi Sebastian,
sorry für die späte Antwort. Wo finde ich das root-Passwort? Ich hoffe, ich habe das nicht selbst vergeben... :-)

**Comment by sreimers** [comment]
Hi Markus,
du kommst über SSH mit den gleichen Zugangsdaten wie im Webinterface rein:
Benutzer: studio
Passwort: studio

Falls du das Passwort im Webinterface geändert hast ist es damit identisch.

Anschließend einfach:

```
$ sudo su
```

**Comment by markusk** [comment]
Oh, danke.
Musste zur mit "-k" aufrufen, dann lief es auch recht weit, bracht dann aber hier ab:

---

Packages (2): hiredis-0.11.0-4  libmicrohttpd-0.9.37-1

Total Download Size:    0.19 MiB
Total Installed Size:   0.51 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages ...
 hiredis-0.11.0-4-armv7h                                                 19.6 KiB   816K/s 00:00 [########################################################] 100%
 libmicrohttpd-0.9.37-1-armv7h                                          177.2 KiB   852K/s 00:00 [########################################################] 100%
(2/2) checking keys in keyring                                                                   [########################################################] 100%
(2/2) checking package integrity                                                                 [########################################################] 100%
(2/2) loading package files                                                                      [########################################################] 100%
(2/2) checking for file conflicts                                                                [########################################################] 100%
(2/2) checking available disk space                                                              [########################################################] 100%
(1/2) installing hiredis                                                                         [########################################################] 100%
(2/2) installing libmicrohttpd                                                                   [########################################################] 100%
Optional dependencies for libmicrohttpd
    file [installed]
    curl [installed]
--1970-01-01 01:53:30--  https://github.com/studio-link/PKGBUILDs/raw/master/jack2/jack2-14.8.0-1-armv7h.pkg.tar.xz
Resolving github.com (github.com)... 192.30.252.130
Connecting to github.com (github.com)|192.30.252.130|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Issued certificate not yet valid.
To connect to github.com insecurely, use `--no-check-certificate'.

**Comment by markusk** [comment]
Ich versuche einfach mal die Neuinstallation. Das macht vielleicht mehr Sinn. Danke erst mal!

**Comment by sreimers** [comment]
Hi Markus,

kurzer Nachtrag noch. Bei der Neuinstallation lässt du den Touch Befehl auf:

/etc/studio-link-community

weg bzw. falls schon gemacht einfach die Datei entfernen und noch einmal Bootstrap ausführen. Ansonsten lädt sich dein Studio Link kein Provisioning File von meinem Server.

**Comment by markusk** [comment]
Neuinstallation (ohne "touch /etc/studio-link-community") durchgeführt. Bricht bei folgendem Fehler ab:

:: Proceed with installation? [Y/n]
:: Retrieving packages ...
 lame-3.99.5-2-armv7h                                                   225.2 KiB  1251K/s 00:00 [########################################################] 100%
 liblo-1:0.28-1-armv7h                                                   42.9 KiB  6.99M/s 00:00 [########################################################] 100%
 mxml-2.9-1-armv7h                                                       91.7 KiB  2.89M/s 00:00 [########################################################] 100%
(9/9) checking keys in keyring                                                                   [########################################################] 100%
(5/9) checking package integrity                                                                 [########################################################] 100%
(5/9) loading package files                                                                      [########################################################] 100%
(9/9) checking for file conflicts                                                                [########################################################] 100%
(9/9) checking available disk space                                                              [########################################################] 100%
(1/9) installing mxml                                                                            [########################################################] 100%
(2/9) installing aj-snapshot                                                                     [########################################################] 100%
(3/9) installing baresip                                                                         [########################################################] 100%
(4/9) installing lame                                                                            [########################################################] 100%
(5/9) installing liblo                                                                           [########################################################] 100%
(6/9) installing jack_capture                                                                    [########################################################] 100%
(7/9) installing libre                                                                           [########################################################] 100%
(8/9) installing librem                                                                          [########################################################] 100%
(9/9) installing opus                                                                            [########################################################] 100%
Job for studio-webapp.service failed. See "systemctl status studio-webapp.service" and "journalctl -xe" for details.
[root@alarm ~]#

**Comment by markusk** [comment]
PS.: Hier noch die Details der Fehler:

[root@alarm ~]# systemctl status studio-webapp.service
- studio-webapp.service - studio-webapp fastcgi
  Loaded: loaded (/etc/systemd/system/studio-webapp.service; enabled; vendor preset: disabled)
  Active: failed (Result: exit-code) since Tue 2015-01-20 22:12:50 CET; 30min ago
  Process: 2682 ExecStartPost=/usr/bin/redis-cli flushall (code=exited, status=1/FAILURE)
  Process: 2681 ExecStart=/opt/studio/bin/gunicorn -w 2 -b 127.0.0.1:5000 --chdir /opt/studio/webapp app:app (code=killed, signal=TERM)
  Main PID: 2681 (code=killed, signal=TERM)

Jan 20 22:12:50 alarm systemd[1]: Starting studio-webapp fastcgi...
Jan 20 22:12:50 alarm systemd[1]: studio-webapp.service: control process exited, code=exited status=1
Jan 20 22:12:50 alarm systemd[1]: Failed to start studio-webapp fastcgi.
Jan 20 22:12:50 alarm systemd[1]: Unit studio-webapp.service entered failed state.
Jan 20 22:12:50 alarm systemd[1]: studio-webapp.service failed.
Jan 20 22:12:50 alarm redis-cli[2682]: Could not connect to Redis at 127.0.0.1:6379: Connection refused
[root@alarm ~]# journalctl -xe
Jan 20 22:12:50 alarm redis-server[2677]: .-`.-``.``\/    _.,_ ''-._
Jan 20 22:12:50 alarm redis-server[2677]: (    '      ,       .-`  | `,    )     Running in stand alone mode
Jan 20 22:12:50 alarm redis-server[2677]: |`-._`-...-` __...-.`-._|'`_.-'|     Port: 6379
Jan 20 22:12:50 alarm redis-server[2677]: |`-._   `._    /     _.-'    |     PID: 2677
Jan 20 22:12:50 alarm redis-server[2677]:`-._    `-._`-./  _.-'    _.-'
Jan 20 22:12:50 alarm redis-server[2677]: |`-._`-._`-.**.-'    _.-'_.-'|
Jan 20 22:12:50 alarm redis-server[2677]: |    `-._`-._        _.-'_.-'    |           http://redis.io
Jan 20 22:12:50 alarm redis-server[2677]: `-._`-._`-.**.-'_.-'    _.-'
Jan 20 22:12:50 alarm redis-server[2677]: |`-._`-._`-.**.-'    _.-'_.-'|
Jan 20 22:12:50 alarm redis-server[2677]: |    `-._`-._        _.-'_.-'    |
Jan 20 22:12:50 alarm redis-server[2677]: `-._`-._`-.**.-'_.-'    _.-'
Jan 20 22:12:50 alarm redis-server[2677]: `-._    `-.__.-'    _.-'
Jan 20 22:12:50 alarm redis-server[2677]:`-._        _.-'
Jan 20 22:12:50 alarm redis-server[2677]: `-.__.-'
Jan 20 22:12:50 alarm redis-server[2677]: [2677] 20 Jan 22:12:50.658 # Server started, Redis version 2.8.19
Jan 20 22:12:50 alarm redis-server[2677]: [2677] 20 Jan 22:12:50.670 # WARNING overcommit_memory is set to 0! Background save may fail under low memory conditio
Jan 20 22:12:50 alarm redis-server[2677]: [2677] 20 Jan 22:12:50.671 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/som
Jan 20 22:12:50 alarm redis-server[2677]: [2677] 20 Jan 22:12:50.675 \* The server is now ready to accept connections on port 6379
Jan 20 22:12:50 alarm redis-cli[2682]: Could not connect to Redis at 127.0.0.1:6379: Connection refused
Jan 20 22:12:57 alarm celery[2679]: [2015-01-20 22:12:57,514: INFO/MainProcess] Connected to redis://localhost:6379/0
Jan 20 22:12:57 alarm celery[2679]: [2015-01-20 22:12:57,609: INFO/MainProcess] mingle: searching for neighbors
Jan 20 22:12:58 alarm celery[2679]: [2015-01-20 22:12:58,660: INFO/MainProcess] mingle: all alone
Jan 20 22:12:58 alarm celery[2679]: [2015-01-20 22:12:58,759: WARNING/MainProcess] celery@alarm ready.
Jan 20 22:17:51 alarm redis-server[2677]: [2677] 20 Jan 22:17:51.031 \* 10 changes in 300 seconds. Saving...
Jan 20 22:17:51 alarm redis-server[2677]: [2677] 20 Jan 22:17:51.032 \* Background saving started by pid 2693
Jan 20 22:17:51 alarm redis-server[2677]: [2693] 20 Jan 22:17:51.073 \* DB saved on disk
Jan 20 22:17:51 alarm redis-server[2677]: [2693] 20 Jan 22:17:51.076 \* RDB: 0 MB of memory used by copy-on-write
Jan 20 22:17:51 alarm redis-server[2677]: [2677] 20 Jan 22:17:51.132 \* Background saving terminated with success
Jan 20 22:22:52 alarm redis-server[2677]: [2677] 20 Jan 22:22:52.072 \* 10 changes in 300 seconds. Saving...
Jan 20 22:22:52 alarm redis-server[2677]: [2677] 20 Jan 22:22:52.073 \* Background saving started by pid 2694
Jan 20 22:22:52 alarm redis-server[2677]: [2694] 20 Jan 22:22:52.131 \* DB saved on disk
Jan 20 22:22:52 alarm redis-server[2677]: [2694] 20 Jan 22:22:52.133 \* RDB: 0 MB of memory used by copy-on-write
Jan 20 22:22:52 alarm redis-server[2677]: [2677] 20 Jan 22:22:52.174 \* Background saving terminated with success
Jan 20 22:24:53 alarm systemd-timesyncd[137]: interval/delta/delay/jitter/drift 2048s/-0.013s/0.001s/0.006s/-19ppm
Jan 20 22:27:53 alarm redis-server[2677]: [2677] 20 Jan 22:27:53.018 \* 10 changes in 300 seconds. Saving...
Jan 20 22:27:54 alarm redis-server[2677]: [2677] 20 Jan 22:27:53.022 \* Background saving started by pid 2695
Jan 20 22:27:54 alarm redis-server[2677]: [2695] 20 Jan 22:27:54.061 \* DB saved on disk
Jan 20 22:27:54 alarm redis-server[2677]: [2695] 20 Jan 22:27:54.063 \* RDB: 0 MB of memory used by copy-on-write
Jan 20 22:27:54 alarm redis-server[2677]: [2677] 20 Jan 22:27:54.126 \* Background saving terminated with success
Jan 20 22:32:55 alarm redis-server[2677]: [2677] 20 Jan 22:32:55.079 \* 10 changes in 300 seconds. Saving...
Jan 20 22:32:55 alarm redis-server[2677]: [2677] 20 Jan 22:32:55.083 \* Background saving started by pid 2696
Jan 20 22:32:55 alarm redis-server[2677]: [2696] 20 Jan 22:32:55.128 \* DB saved on disk
Jan 20 22:32:55 alarm redis-server[2677]: [2696] 20 Jan 22:32:55.130 \* RDB: 0 MB of memory used by copy-on-write
Jan 20 22:32:55 alarm redis-server[2677]: [2677] 20 Jan 22:32:55.183 \* Background saving terminated with success
Jan 20 22:37:56 alarm redis-server[2677]: [2677] 20 Jan 22:37:56.034 \* 10 changes in 300 seconds. Saving...
Jan 20 22:37:56 alarm redis-server[2677]: [2677] 20 Jan 22:37:56.035 \* Background saving started by pid 2697
Jan 20 22:37:56 alarm redis-server[2677]: [2697] 20 Jan 22:37:56.075 \* DB saved on disk
Jan 20 22:37:56 alarm redis-server[2677]: [2697] 20 Jan 22:37:56.078 \* RDB: 0 MB of memory used by copy-on-write
Jan 20 22:37:56 alarm redis-server[2677]: [2677] 20 Jan 22:37:56.135 \* Background saving terminated with success
Jan 20 22:42:57 alarm redis-server[2677]: [2677] 20 Jan 22:42:57.096 \* 10 changes in 300 seconds. Saving...
Jan 20 22:42:57 alarm redis-server[2677]: [2677] 20 Jan 22:42:57.100 \* Background saving started by pid 2698
Jan 20 22:42:57 alarm redis-server[2677]: [2698] 20 Jan 22:42:57.146 \* DB saved on disk
Jan 20 22:42:57 alarm redis-server[2677]: [2698] 20 Jan 22:42:57.150 \* RDB: 0 MB of memory used by copy-on-write
Jan 20 22:42:57 alarm redis-server[2677]: [2677] 20 Jan 22:42:57.201 \* Background saving terminated with success
lines 1413-1466/1466 (END)

**Comment by sreimers** [comment]
Moin Markus,

du kannst den bootstrap Befehl noch einmal laufen lassen. Ich habe gerade einen workaround für redis hochgeladen.
Am besten einmal mit:

$ curl -L https://raw.githubusercontent.com/studio-link/images/master/bootstrap.sh | bash -x

dann wird auch die aktuelle Position im Skript ausgegeben. Neuinstallieren brauchst du nicht. Nach einem Neustart sollte schon jetzt die Web-Oberfäche kommen. Nur das Provisioning wurde ausgelassen.

**Comment by markusk** [comment]
## YEAH! Hat alles geklappt jetzt. Danke!! Jetzt wird's Zeit, das Maik P. seinen noch aktualisiert und ich seinen live im Robotiklabor-Podcast zur "Einwahl" testen kann. :-)

**\* Bootstrap finished! Please reboot now! ***
- /usr/bin/redis-cli set reboot_required true
  OK
